### PR TITLE
fix outdated docstrings

### PR DESCRIPTION
**Pull request by Doublonmousse**
There was some outdated doctest in the `utils.py` dating from the last refactor (where a function name was changed but not the associated doctest). I made sure that 

```py
python -m doctest utils.py
```
was successful.

Are doctest not part of the current testing CI ? Seems like that could be fixed with a change of configuration for `pytest` (see here : https://docs.pytest.org/en/7.1.x/how-to/doctest.html)

### CODE REVIEW

**Comment by mtezzele** [comment]
Thank you so much @Doublonmousse! @fandreuz I think we can add this to the CI, what do you think?

**Comment by mtezzele** [comment]
@Doublonmousse please run `black` on the modified file.

**Comment by Doublonmousse** [comment]
Okay. I've reformatted the file using `black`.

Seems like using `doctestplus` you can run the following command 
```py
pytest pydmd/ --doctest-only
```
to only test doctest.

Though it doesn't seem like it's the only doctest failing doing that ...

image

**Comment by Doublonmousse** [comment]
Argh ... seems all `.. code-block:: python` are tested with this option, and without surprises all such code that suppose that you have `dmd` as a dmd object before running them fail

**Pull request merged**
