### PR TITLE
Fix not returning the video with added noise in Tutorial12: compressedDMD

### PR DESCRIPTION
**Pull request by karlic-luka**
There's an option to add the noise to the original frames. However, after adding gaussian noise, the function returns the original frames.

### CODE REVIEW

**Comment by mtezzele** [comment]
Hi @karlic-luka. Thank you for spotting the bug. Could you please make the edit directly on the notebook? We have CI to generate the python files.

**Comment by karlic-luka** [comment]
Hi @mtezzele, no worries. I added it in the .ipynb also :)

**Comment by mtezzele** [comment]
@fandreuz can we merge this PR?

**Comment by fandreuz** [comment]
Didn't have time to look into the problem this week, I'll try to have a look today @mtezzele

**Comment by fandreuz** [comment]
@mtezzele the problem is caused by another tutorial, we can merge this MR as it seems to be unrelated to the failure

**Pull request merged**
