### PR TITLE
Add partial_amplitudes as an output of mrDMD

### PR DESCRIPTION
**Pull request by roxyboy**
This PR addresses #474 so as to also save `partial_amplitudes` per level for the outputs from multi-resolution DMD.

### CODE REVIEW

**Comment by mtezzele** [comment]
Hi @roxyboy, thank you for the PR. Could you please add a small test to check the new method? Just have a look at this file: `tests/test_mrdmd.py`

**Comment by mtezzele** [comment]
@roxyboy you also need to rebase this branch, please. If you need help just let me know.

**Comment by roxyboy** [comment]
> @roxyboy you also need to rebase this branch, please. If you need help just let me know.

Thank you for the review. I could use some help regarding rebasing the branch...
I will work on adding a test.

**Comment by roxyboy** [comment]
I've been trying to push changes that I added to `test_mrdmd.py`:

```
def test_partial_amplitudes1():
    max_level = 5
    level = 2
    rank = 2
    dmd = DMD(svd_rank=rank)
    mrdmd = MrDMD(dmd, max_level=max_level, max_cycles=2)
    mrdmd.fit(X=sample_data)
    pamps = mrdmd.partial_amplitudes(level)
    assert pamps.shape == (rank * 2**level,)


def test_partial_amplitudes2():
    max_level = 5
    level = 2
    rank = 2
    dmd = DMD(svd_rank=rank)
    mrdmd = MrDMD(dmd, max_level=6, max_cycles=2)
    mrdmd.fit(X=sample_data)
    pamps = mrdmd.partial_amplitudes(level, 3)
    assert pamps.shape == (rank,)
```
but I'm getting the following error:
```
$ git push origin par_amp
Username for 'https://github.com': roxyboy
Password for 'https://roxyboy@github.com': 
To https://github.com/roxyboy/PyDMD.git
 ! [rejected]        par_amp -> par_amp (fetch first)
error: failed to push some refs to 'https://github.com/roxyboy/PyDMD.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Sorry for the elementary question but I've never been able to figure out how to push to branches that have external collaborations. Could you advise how I should proceed?

**Comment by mtezzele** [comment]
@roxyboy you need to fetch and rebase you branch against the master branch of the package. Do the following from your local branch:

1. `git fetch remote_name_you_assigned_to_pydmd` (let's call it `upstream` for this example, you can retrieve it with `git remote -v`)
2. `git rebase -i upstream/master`
3. save the text file that the terminal presents you, exit
4. `git push origin par_amp` (if you get an error here, you should use the `-f` flag)

**Comment by roxyboy** [comment]
The `-f` flag seems to have done the trick.

**Pull request merged**
