### PR TITLE
PiDMD Tutorial

### PR DESCRIPTION
**Pull request by sichinaga**
Hi everyone!

Apologies that this took some time, but I've created a lengthy tutorial for the `PiDMD` module. It basically walks users through a brief overview of the theory of PiDMD and skims through all of the module's available manifolds. It also includes a brief comparison of DMD and PiDMD when applied to a toy dataset.

Currently, this PR only includes the Jupyter Notebook, but I will add the corresponding `.py` file once we feel this tutorial is good to go! 😄 

Edit: I've added the `.py` file thinking it might help me pass some tests, but maybe not? If someone could fill me in on how to get the tests passing, that would be much appreciated. :)

### CODE REVIEW

**Comment by mtezzele** [comment]
@sichinaga I think this is a great tutorial! Thanks for the contribution.
Just add it to the readme table in the tutorials folder, please.

**Comment by fandreuz** [comment]
Hi @sichinaga, we can rely on the GitHub action to automatically generate the `.py` file based on your notebook after we merge this this, so there's no need to attach it to the PR. The tutorial looks very good!

**Comment by ndem0** [comment]
Very nice, green light also for me!
Thanks!

**Comment by sichinaga** [comment]
Thank you all for reviewing the tutorial! I removed the `.py` file so that GitHub can automatically generate it, and I added the tutorial to the readme as per your suggestions. Let me know if anything else needs fixing! :)

**Pull request merged**
